name: 'PackageCloud'
description: 'Upload deb to package cloud.'
inputs:
  repo:
    description: 'destination repository'
    required: 'true'
  path:
    description: 'dir containing debs'
    required: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.path }}
